/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AdsProviderControllersController
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T15:41:52.549-07:00")
public class AdsProviderControllersController {
  @SerializedName("dc_address")
  private String dcAddress = null;

  @SerializedName("dc_name")
  private String dcName = null;

  @SerializedName("id")
  private String id = null;

  public AdsProviderControllersController dcAddress(String dcAddress) {
    this.dcAddress = dcAddress;
    return this;
  }

   /**
   * Specifies the address for the domain controller.
   * @return dcAddress
  **/
  @ApiModelProperty(value = "Specifies the address for the domain controller.")
  public String getDcAddress() {
    return dcAddress;
  }

  public void setDcAddress(String dcAddress) {
    this.dcAddress = dcAddress;
  }

  public AdsProviderControllersController dcName(String dcName) {
    this.dcName = dcName;
    return this;
  }

   /**
   * Specifies the name of the domain controller.
   * @return dcName
  **/
  @ApiModelProperty(value = "Specifies the name of the domain controller.")
  public String getDcName() {
    return dcName;
  }

  public void setDcName(String dcName) {
    this.dcName = dcName;
  }

  public AdsProviderControllersController id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Specifies the address for the domain controller. This value is the same as the &#39;dc_address&#39; value.
   * @return id
  **/
  @ApiModelProperty(value = "Specifies the address for the domain controller. This value is the same as the 'dc_address' value.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdsProviderControllersController adsProviderControllersController = (AdsProviderControllersController) o;
    return Objects.equals(this.dcAddress, adsProviderControllersController.dcAddress) &&
        Objects.equals(this.dcName, adsProviderControllersController.dcName) &&
        Objects.equals(this.id, adsProviderControllersController.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dcAddress, dcName, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdsProviderControllersController {\n");
    
    sb.append("    dcAddress: ").append(toIndentedString(dcAddress)).append("\n");
    sb.append("    dcName: ").append(toIndentedString(dcName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

