/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Flush security objects cache.
 */
@ApiModel(description = "Flush security objects cache.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T09:38:03.973-07:00")
public class AuthCacheItem {
  @SerializedName("all")
  private String all = null;

  @SerializedName("gid")
  private Integer gid = null;

  @SerializedName("group_name")
  private String groupName = null;

  @SerializedName("provider")
  private String provider = null;

  @SerializedName("sid")
  private String sid = null;

  @SerializedName("uid")
  private Integer uid = null;

  @SerializedName("user_name")
  private String userName = null;

  public AuthCacheItem all(String all) {
    this.all = all;
    return this;
  }

   /**
   * Flush all objects in cache for access zone.
   * @return all
  **/
  @ApiModelProperty(value = "Flush all objects in cache for access zone.")
  public String getAll() {
    return all;
  }

  public void setAll(String all) {
    this.all = all;
  }

  public AuthCacheItem gid(Integer gid) {
    this.gid = gid;
    return this;
  }

   /**
   * Flush objects in cache for access zone specified by GID.
   * minimum: 0
   * maximum: 4294967295
   * @return gid
  **/
  @ApiModelProperty(value = "Flush objects in cache for access zone specified by GID.")
  public Integer getGid() {
    return gid;
  }

  public void setGid(Integer gid) {
    this.gid = gid;
  }

  public AuthCacheItem groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * Flush objects in cache for access zone specified by group name.
   * @return groupName
  **/
  @ApiModelProperty(value = "Flush objects in cache for access zone specified by group name.")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public AuthCacheItem provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * Flush objects in cache for access zone specified by authentication provider.
   * @return provider
  **/
  @ApiModelProperty(value = "Flush objects in cache for access zone specified by authentication provider.")
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }

  public AuthCacheItem sid(String sid) {
    this.sid = sid;
    return this;
  }

   /**
   * Flush objects in cache for access zone specified by SID.
   * @return sid
  **/
  @ApiModelProperty(value = "Flush objects in cache for access zone specified by SID.")
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public AuthCacheItem uid(Integer uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Flush objects in cache for access zone specified by UID.
   * minimum: 0
   * maximum: 4294967295
   * @return uid
  **/
  @ApiModelProperty(value = "Flush objects in cache for access zone specified by UID.")
  public Integer getUid() {
    return uid;
  }

  public void setUid(Integer uid) {
    this.uid = uid;
  }

  public AuthCacheItem userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Flush objects in cache for access zone specified by user name.
   * @return userName
  **/
  @ApiModelProperty(value = "Flush objects in cache for access zone specified by user name.")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthCacheItem authCacheItem = (AuthCacheItem) o;
    return Objects.equals(this.all, authCacheItem.all) &&
        Objects.equals(this.gid, authCacheItem.gid) &&
        Objects.equals(this.groupName, authCacheItem.groupName) &&
        Objects.equals(this.provider, authCacheItem.provider) &&
        Objects.equals(this.sid, authCacheItem.sid) &&
        Objects.equals(this.uid, authCacheItem.uid) &&
        Objects.equals(this.userName, authCacheItem.userName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(all, gid, groupName, provider, sid, uid, userName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthCacheItem {\n");
    
    sb.append("    all: ").append(toIndentedString(all)).append("\n");
    sb.append("    gid: ").append(toIndentedString(gid)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

