/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AuthAccessAccessItemShareSharePermissionsShareRelevantAce
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T15:41:52.549-07:00")
public class AuthAccessAccessItemShareSharePermissionsShareRelevantAce {
  @SerializedName("ace")
  private String ace = null;

  public AuthAccessAccessItemShareSharePermissionsShareRelevantAce ace(String ace) {
    this.ace = ace;
    return this;
  }

   /**
   * Specifies properties for an Access Control Entry
   * @return ace
  **/
  @ApiModelProperty(value = "Specifies properties for an Access Control Entry")
  public String getAce() {
    return ace;
  }

  public void setAce(String ace) {
    this.ace = ace;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthAccessAccessItemShareSharePermissionsShareRelevantAce authAccessAccessItemShareSharePermissionsShareRelevantAce = (AuthAccessAccessItemShareSharePermissionsShareRelevantAce) o;
    return Objects.equals(this.ace, authAccessAccessItemShareSharePermissionsShareRelevantAce.ace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthAccessAccessItemShareSharePermissionsShareRelevantAce {\n");
    
    sb.append("    ace: ").append(toIndentedString(ace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

