/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ClusterNodeStateServicelightExtendedExtended;
import io.swagger.client.model.NodeStateReadonlyExtended;
import io.swagger.client.model.NodeStateSmartfailExtended;
import java.io.IOException;

/**
 * ClusterNodeStateExtendedExtended
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T09:38:03.973-07:00")
public class ClusterNodeStateExtendedExtended {
  @SerializedName("readonly")
  private NodeStateReadonlyExtended readonly = null;

  @SerializedName("servicelight")
  private ClusterNodeStateServicelightExtendedExtended servicelight = null;

  @SerializedName("smartfail")
  private NodeStateSmartfailExtended smartfail = null;

  public ClusterNodeStateExtendedExtended readonly(NodeStateReadonlyExtended readonly) {
    this.readonly = readonly;
    return this;
  }

   /**
   * Node readonly state.
   * @return readonly
  **/
  @ApiModelProperty(value = "Node readonly state.")
  public NodeStateReadonlyExtended getReadonly() {
    return readonly;
  }

  public void setReadonly(NodeStateReadonlyExtended readonly) {
    this.readonly = readonly;
  }

  public ClusterNodeStateExtendedExtended servicelight(ClusterNodeStateServicelightExtendedExtended servicelight) {
    this.servicelight = servicelight;
    return this;
  }

   /**
   * Node service light state.
   * @return servicelight
  **/
  @ApiModelProperty(value = "Node service light state.")
  public ClusterNodeStateServicelightExtendedExtended getServicelight() {
    return servicelight;
  }

  public void setServicelight(ClusterNodeStateServicelightExtendedExtended servicelight) {
    this.servicelight = servicelight;
  }

  public ClusterNodeStateExtendedExtended smartfail(NodeStateSmartfailExtended smartfail) {
    this.smartfail = smartfail;
    return this;
  }

   /**
   * Node smartfail state.
   * @return smartfail
  **/
  @ApiModelProperty(value = "Node smartfail state.")
  public NodeStateSmartfailExtended getSmartfail() {
    return smartfail;
  }

  public void setSmartfail(NodeStateSmartfailExtended smartfail) {
    this.smartfail = smartfail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterNodeStateExtendedExtended clusterNodeStateExtendedExtended = (ClusterNodeStateExtendedExtended) o;
    return Objects.equals(this.readonly, clusterNodeStateExtendedExtended.readonly) &&
        Objects.equals(this.servicelight, clusterNodeStateExtendedExtended.servicelight) &&
        Objects.equals(this.smartfail, clusterNodeStateExtendedExtended.smartfail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(readonly, servicelight, smartfail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterNodeStateExtendedExtended {\n");
    
    sb.append("    readonly: ").append(toIndentedString(readonly)).append("\n");
    sb.append("    servicelight: ").append(toIndentedString(servicelight)).append("\n");
    sb.append("    smartfail: ").append(toIndentedString(smartfail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

