/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Filesystem statistics
 */
@ApiModel(description = "Filesystem statistics")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T15:41:52.549-07:00")
public class ClusterStatfs {
  @SerializedName("f_bavail")
  private Integer fBavail = null;

  @SerializedName("f_bfree")
  private Integer fBfree = null;

  @SerializedName("f_blocks")
  private Integer fBlocks = null;

  @SerializedName("f_bsize")
  private Integer fBsize = null;

  @SerializedName("f_ffree")
  private Integer fFfree = null;

  @SerializedName("f_files")
  private Integer fFiles = null;

  @SerializedName("f_flags")
  private Integer fFlags = null;

  @SerializedName("f_fstypename")
  private String fFstypename = null;

  @SerializedName("f_iosize")
  private Integer fIosize = null;

  @SerializedName("f_mntfromname")
  private String fMntfromname = null;

  @SerializedName("f_mntonname")
  private String fMntonname = null;

  @SerializedName("f_namemax")
  private Integer fNamemax = null;

  @SerializedName("f_owner")
  private Integer fOwner = null;

  @SerializedName("f_type")
  private Integer fType = null;

  @SerializedName("f_version")
  private Integer fVersion = null;

  public ClusterStatfs fBavail(Integer fBavail) {
    this.fBavail = fBavail;
    return this;
  }

   /**
   * The number of free blocks available to non-superuser.
   * @return fBavail
  **/
  @ApiModelProperty(required = true, value = "The number of free blocks available to non-superuser.")
  public Integer getFBavail() {
    return fBavail;
  }

  public void setFBavail(Integer fBavail) {
    this.fBavail = fBavail;
  }

  public ClusterStatfs fBfree(Integer fBfree) {
    this.fBfree = fBfree;
    return this;
  }

   /**
   * The number of free blocks in the filesystem.
   * @return fBfree
  **/
  @ApiModelProperty(required = true, value = "The number of free blocks in the filesystem.")
  public Integer getFBfree() {
    return fBfree;
  }

  public void setFBfree(Integer fBfree) {
    this.fBfree = fBfree;
  }

  public ClusterStatfs fBlocks(Integer fBlocks) {
    this.fBlocks = fBlocks;
    return this;
  }

   /**
   * The total number of data blocks in the filesystem.
   * @return fBlocks
  **/
  @ApiModelProperty(required = true, value = "The total number of data blocks in the filesystem.")
  public Integer getFBlocks() {
    return fBlocks;
  }

  public void setFBlocks(Integer fBlocks) {
    this.fBlocks = fBlocks;
  }

  public ClusterStatfs fBsize(Integer fBsize) {
    this.fBsize = fBsize;
    return this;
  }

   /**
   * The filesystem fragment size.
   * @return fBsize
  **/
  @ApiModelProperty(required = true, value = "The filesystem fragment size.")
  public Integer getFBsize() {
    return fBsize;
  }

  public void setFBsize(Integer fBsize) {
    this.fBsize = fBsize;
  }

  public ClusterStatfs fFfree(Integer fFfree) {
    this.fFfree = fFfree;
    return this;
  }

   /**
   * The number of free nodes available to non-superuser.
   * @return fFfree
  **/
  @ApiModelProperty(required = true, value = "The number of free nodes available to non-superuser.")
  public Integer getFFfree() {
    return fFfree;
  }

  public void setFFfree(Integer fFfree) {
    this.fFfree = fFfree;
  }

  public ClusterStatfs fFiles(Integer fFiles) {
    this.fFiles = fFiles;
    return this;
  }

   /**
   * The total number of file nodes in the filesystem.
   * @return fFiles
  **/
  @ApiModelProperty(required = true, value = "The total number of file nodes in the filesystem.")
  public Integer getFFiles() {
    return fFiles;
  }

  public void setFFiles(Integer fFiles) {
    this.fFiles = fFiles;
  }

  public ClusterStatfs fFlags(Integer fFlags) {
    this.fFlags = fFlags;
    return this;
  }

   /**
   * A copy of the mount exported flags.
   * @return fFlags
  **/
  @ApiModelProperty(required = true, value = "A copy of the mount exported flags.")
  public Integer getFFlags() {
    return fFlags;
  }

  public void setFFlags(Integer fFlags) {
    this.fFlags = fFlags;
  }

  public ClusterStatfs fFstypename(String fFstypename) {
    this.fFstypename = fFstypename;
    return this;
  }

   /**
   * The filesystem type name.
   * @return fFstypename
  **/
  @ApiModelProperty(required = true, value = "The filesystem type name.")
  public String getFFstypename() {
    return fFstypename;
  }

  public void setFFstypename(String fFstypename) {
    this.fFstypename = fFstypename;
  }

  public ClusterStatfs fIosize(Integer fIosize) {
    this.fIosize = fIosize;
    return this;
  }

   /**
   * The optimal transfer block size.
   * @return fIosize
  **/
  @ApiModelProperty(required = true, value = "The optimal transfer block size.")
  public Integer getFIosize() {
    return fIosize;
  }

  public void setFIosize(Integer fIosize) {
    this.fIosize = fIosize;
  }

  public ClusterStatfs fMntfromname(String fMntfromname) {
    this.fMntfromname = fMntfromname;
    return this;
  }

   /**
   * The name of the mounted filesystem.
   * @return fMntfromname
  **/
  @ApiModelProperty(required = true, value = "The name of the mounted filesystem.")
  public String getFMntfromname() {
    return fMntfromname;
  }

  public void setFMntfromname(String fMntfromname) {
    this.fMntfromname = fMntfromname;
  }

  public ClusterStatfs fMntonname(String fMntonname) {
    this.fMntonname = fMntonname;
    return this;
  }

   /**
   * The directory that the filesystem is mounted on.
   * @return fMntonname
  **/
  @ApiModelProperty(required = true, value = "The directory that the filesystem is mounted on.")
  public String getFMntonname() {
    return fMntonname;
  }

  public void setFMntonname(String fMntonname) {
    this.fMntonname = fMntonname;
  }

  public ClusterStatfs fNamemax(Integer fNamemax) {
    this.fNamemax = fNamemax;
    return this;
  }

   /**
   * The maximum length of a file name.
   * @return fNamemax
  **/
  @ApiModelProperty(required = true, value = "The maximum length of a file name.")
  public Integer getFNamemax() {
    return fNamemax;
  }

  public void setFNamemax(Integer fNamemax) {
    this.fNamemax = fNamemax;
  }

  public ClusterStatfs fOwner(Integer fOwner) {
    this.fOwner = fOwner;
    return this;
  }

   /**
   * The ID of the user that mounted the filesystem.
   * @return fOwner
  **/
  @ApiModelProperty(required = true, value = "The ID of the user that mounted the filesystem.")
  public Integer getFOwner() {
    return fOwner;
  }

  public void setFOwner(Integer fOwner) {
    this.fOwner = fOwner;
  }

  public ClusterStatfs fType(Integer fType) {
    this.fType = fType;
    return this;
  }

   /**
   * The type of the filesystem.
   * @return fType
  **/
  @ApiModelProperty(required = true, value = "The type of the filesystem.")
  public Integer getFType() {
    return fType;
  }

  public void setFType(Integer fType) {
    this.fType = fType;
  }

  public ClusterStatfs fVersion(Integer fVersion) {
    this.fVersion = fVersion;
    return this;
  }

   /**
   * The structure version number.
   * @return fVersion
  **/
  @ApiModelProperty(required = true, value = "The structure version number.")
  public Integer getFVersion() {
    return fVersion;
  }

  public void setFVersion(Integer fVersion) {
    this.fVersion = fVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterStatfs clusterStatfs = (ClusterStatfs) o;
    return Objects.equals(this.fBavail, clusterStatfs.fBavail) &&
        Objects.equals(this.fBfree, clusterStatfs.fBfree) &&
        Objects.equals(this.fBlocks, clusterStatfs.fBlocks) &&
        Objects.equals(this.fBsize, clusterStatfs.fBsize) &&
        Objects.equals(this.fFfree, clusterStatfs.fFfree) &&
        Objects.equals(this.fFiles, clusterStatfs.fFiles) &&
        Objects.equals(this.fFlags, clusterStatfs.fFlags) &&
        Objects.equals(this.fFstypename, clusterStatfs.fFstypename) &&
        Objects.equals(this.fIosize, clusterStatfs.fIosize) &&
        Objects.equals(this.fMntfromname, clusterStatfs.fMntfromname) &&
        Objects.equals(this.fMntonname, clusterStatfs.fMntonname) &&
        Objects.equals(this.fNamemax, clusterStatfs.fNamemax) &&
        Objects.equals(this.fOwner, clusterStatfs.fOwner) &&
        Objects.equals(this.fType, clusterStatfs.fType) &&
        Objects.equals(this.fVersion, clusterStatfs.fVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fBavail, fBfree, fBlocks, fBsize, fFfree, fFiles, fFlags, fFstypename, fIosize, fMntfromname, fMntonname, fNamemax, fOwner, fType, fVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterStatfs {\n");
    
    sb.append("    fBavail: ").append(toIndentedString(fBavail)).append("\n");
    sb.append("    fBfree: ").append(toIndentedString(fBfree)).append("\n");
    sb.append("    fBlocks: ").append(toIndentedString(fBlocks)).append("\n");
    sb.append("    fBsize: ").append(toIndentedString(fBsize)).append("\n");
    sb.append("    fFfree: ").append(toIndentedString(fFfree)).append("\n");
    sb.append("    fFiles: ").append(toIndentedString(fFiles)).append("\n");
    sb.append("    fFlags: ").append(toIndentedString(fFlags)).append("\n");
    sb.append("    fFstypename: ").append(toIndentedString(fFstypename)).append("\n");
    sb.append("    fIosize: ").append(toIndentedString(fIosize)).append("\n");
    sb.append("    fMntfromname: ").append(toIndentedString(fMntfromname)).append("\n");
    sb.append("    fMntonname: ").append(toIndentedString(fMntonname)).append("\n");
    sb.append("    fNamemax: ").append(toIndentedString(fNamemax)).append("\n");
    sb.append("    fOwner: ").append(toIndentedString(fOwner)).append("\n");
    sb.append("    fType: ").append(toIndentedString(fType)).append("\n");
    sb.append("    fVersion: ").append(toIndentedString(fVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

