/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ClusterEmailSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T15:41:52.549-07:00")
public class ClusterEmailSettings {
  /**
   * This setting determines how notifications will be batched together to be sent by email.  &#39;none&#39; means each notification will be sent separately.  &#39;severity&#39; means notifications of the same severity will be sent together.  &#39;category&#39; means notifications of the same category will be sent together.  &#39;all&#39; means all notifications will be batched together and sent in a single email.
   */
  @JsonAdapter(BatchModeEnum.Adapter.class)
  public enum BatchModeEnum {
    ALL("all"),
    
    SEVERITY("severity"),
    
    CATEGORY("category"),
    
    NONE("none");

    private String value;

    BatchModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BatchModeEnum fromValue(String text) {
      for (BatchModeEnum b : BatchModeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<BatchModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BatchModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BatchModeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return BatchModeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("batch_mode")
  private BatchModeEnum batchMode = null;

  @SerializedName("mail_relay")
  private String mailRelay = null;

  @SerializedName("mail_sender")
  private String mailSender = null;

  @SerializedName("mail_subject")
  private String mailSubject = null;

  @SerializedName("smtp_auth_passwd_set")
  private Boolean smtpAuthPasswdSet = null;

  /**
   * The type of secure communication protocol to use if SMTP is being used.  If &#39;none&#39;, plain text will be used, if &#39;starttls&#39;, the encrypted STARTTLS protocol will be used.
   */
  @JsonAdapter(SmtpAuthSecurityEnum.Adapter.class)
  public enum SmtpAuthSecurityEnum {
    NONE("none"),
    
    STARTTLS("starttls");

    private String value;

    SmtpAuthSecurityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SmtpAuthSecurityEnum fromValue(String text) {
      for (SmtpAuthSecurityEnum b : SmtpAuthSecurityEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SmtpAuthSecurityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SmtpAuthSecurityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SmtpAuthSecurityEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SmtpAuthSecurityEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("smtp_auth_security")
  private SmtpAuthSecurityEnum smtpAuthSecurity = null;

  @SerializedName("smtp_auth_username")
  private String smtpAuthUsername = null;

  @SerializedName("smtp_port")
  private Integer smtpPort = null;

  @SerializedName("use_smtp_auth")
  private Boolean useSmtpAuth = null;

  @SerializedName("user_template")
  private String userTemplate = null;

  public ClusterEmailSettings batchMode(BatchModeEnum batchMode) {
    this.batchMode = batchMode;
    return this;
  }

   /**
   * This setting determines how notifications will be batched together to be sent by email.  &#39;none&#39; means each notification will be sent separately.  &#39;severity&#39; means notifications of the same severity will be sent together.  &#39;category&#39; means notifications of the same category will be sent together.  &#39;all&#39; means all notifications will be batched together and sent in a single email.
   * @return batchMode
  **/
  @ApiModelProperty(required = true, value = "This setting determines how notifications will be batched together to be sent by email.  'none' means each notification will be sent separately.  'severity' means notifications of the same severity will be sent together.  'category' means notifications of the same category will be sent together.  'all' means all notifications will be batched together and sent in a single email.")
  public BatchModeEnum getBatchMode() {
    return batchMode;
  }

  public void setBatchMode(BatchModeEnum batchMode) {
    this.batchMode = batchMode;
  }

  public ClusterEmailSettings mailRelay(String mailRelay) {
    this.mailRelay = mailRelay;
    return this;
  }

   /**
   * The address of the SMTP server to be used for relaying the notification messages.  An SMTP server is required in order to send notifications.  If this string is empty, no emails will be sent.
   * @return mailRelay
  **/
  @ApiModelProperty(required = true, value = "The address of the SMTP server to be used for relaying the notification messages.  An SMTP server is required in order to send notifications.  If this string is empty, no emails will be sent.")
  public String getMailRelay() {
    return mailRelay;
  }

  public void setMailRelay(String mailRelay) {
    this.mailRelay = mailRelay;
  }

  public ClusterEmailSettings mailSender(String mailSender) {
    this.mailSender = mailSender;
    return this;
  }

   /**
   * The full email address that will appear as the sender of notification messages.
   * @return mailSender
  **/
  @ApiModelProperty(required = true, value = "The full email address that will appear as the sender of notification messages.")
  public String getMailSender() {
    return mailSender;
  }

  public void setMailSender(String mailSender) {
    this.mailSender = mailSender;
  }

  public ClusterEmailSettings mailSubject(String mailSubject) {
    this.mailSubject = mailSubject;
    return this;
  }

   /**
   * The subject line for notification messages from this cluster.
   * @return mailSubject
  **/
  @ApiModelProperty(required = true, value = "The subject line for notification messages from this cluster.")
  public String getMailSubject() {
    return mailSubject;
  }

  public void setMailSubject(String mailSubject) {
    this.mailSubject = mailSubject;
  }

  public ClusterEmailSettings smtpAuthPasswdSet(Boolean smtpAuthPasswdSet) {
    this.smtpAuthPasswdSet = smtpAuthPasswdSet;
    return this;
  }

   /**
   * Indicates if an SMTP authentication password is set.
   * @return smtpAuthPasswdSet
  **/
  @ApiModelProperty(required = true, value = "Indicates if an SMTP authentication password is set.")
  public Boolean isSmtpAuthPasswdSet() {
    return smtpAuthPasswdSet;
  }

  public void setSmtpAuthPasswdSet(Boolean smtpAuthPasswdSet) {
    this.smtpAuthPasswdSet = smtpAuthPasswdSet;
  }

  public ClusterEmailSettings smtpAuthSecurity(SmtpAuthSecurityEnum smtpAuthSecurity) {
    this.smtpAuthSecurity = smtpAuthSecurity;
    return this;
  }

   /**
   * The type of secure communication protocol to use if SMTP is being used.  If &#39;none&#39;, plain text will be used, if &#39;starttls&#39;, the encrypted STARTTLS protocol will be used.
   * @return smtpAuthSecurity
  **/
  @ApiModelProperty(required = true, value = "The type of secure communication protocol to use if SMTP is being used.  If 'none', plain text will be used, if 'starttls', the encrypted STARTTLS protocol will be used.")
  public SmtpAuthSecurityEnum getSmtpAuthSecurity() {
    return smtpAuthSecurity;
  }

  public void setSmtpAuthSecurity(SmtpAuthSecurityEnum smtpAuthSecurity) {
    this.smtpAuthSecurity = smtpAuthSecurity;
  }

  public ClusterEmailSettings smtpAuthUsername(String smtpAuthUsername) {
    this.smtpAuthUsername = smtpAuthUsername;
    return this;
  }

   /**
   * Username to authenticate with if SMTP authentication is being used.
   * @return smtpAuthUsername
  **/
  @ApiModelProperty(required = true, value = "Username to authenticate with if SMTP authentication is being used.")
  public String getSmtpAuthUsername() {
    return smtpAuthUsername;
  }

  public void setSmtpAuthUsername(String smtpAuthUsername) {
    this.smtpAuthUsername = smtpAuthUsername;
  }

  public ClusterEmailSettings smtpPort(Integer smtpPort) {
    this.smtpPort = smtpPort;
    return this;
  }

   /**
   * The port on the SMTP server to be used for relaying the notification messages.  
   * @return smtpPort
  **/
  @ApiModelProperty(required = true, value = "The port on the SMTP server to be used for relaying the notification messages.  ")
  public Integer getSmtpPort() {
    return smtpPort;
  }

  public void setSmtpPort(Integer smtpPort) {
    this.smtpPort = smtpPort;
  }

  public ClusterEmailSettings useSmtpAuth(Boolean useSmtpAuth) {
    this.useSmtpAuth = useSmtpAuth;
    return this;
  }

   /**
   * If true, this cluster will send SMTP authentication credentials to the SMTP relay server in order to send its notification emails.  If false, the cluster will attempt to send its notification emails without authentication.
   * @return useSmtpAuth
  **/
  @ApiModelProperty(required = true, value = "If true, this cluster will send SMTP authentication credentials to the SMTP relay server in order to send its notification emails.  If false, the cluster will attempt to send its notification emails without authentication.")
  public Boolean isUseSmtpAuth() {
    return useSmtpAuth;
  }

  public void setUseSmtpAuth(Boolean useSmtpAuth) {
    this.useSmtpAuth = useSmtpAuth;
  }

  public ClusterEmailSettings userTemplate(String userTemplate) {
    this.userTemplate = userTemplate;
    return this;
  }

   /**
   * Location of a custom template file that can be used to specify the layout of the notification emails.
   * @return userTemplate
  **/
  @ApiModelProperty(value = "Location of a custom template file that can be used to specify the layout of the notification emails.")
  public String getUserTemplate() {
    return userTemplate;
  }

  public void setUserTemplate(String userTemplate) {
    this.userTemplate = userTemplate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterEmailSettings clusterEmailSettings = (ClusterEmailSettings) o;
    return Objects.equals(this.batchMode, clusterEmailSettings.batchMode) &&
        Objects.equals(this.mailRelay, clusterEmailSettings.mailRelay) &&
        Objects.equals(this.mailSender, clusterEmailSettings.mailSender) &&
        Objects.equals(this.mailSubject, clusterEmailSettings.mailSubject) &&
        Objects.equals(this.smtpAuthPasswdSet, clusterEmailSettings.smtpAuthPasswdSet) &&
        Objects.equals(this.smtpAuthSecurity, clusterEmailSettings.smtpAuthSecurity) &&
        Objects.equals(this.smtpAuthUsername, clusterEmailSettings.smtpAuthUsername) &&
        Objects.equals(this.smtpPort, clusterEmailSettings.smtpPort) &&
        Objects.equals(this.useSmtpAuth, clusterEmailSettings.useSmtpAuth) &&
        Objects.equals(this.userTemplate, clusterEmailSettings.userTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchMode, mailRelay, mailSender, mailSubject, smtpAuthPasswdSet, smtpAuthSecurity, smtpAuthUsername, smtpPort, useSmtpAuth, userTemplate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterEmailSettings {\n");
    
    sb.append("    batchMode: ").append(toIndentedString(batchMode)).append("\n");
    sb.append("    mailRelay: ").append(toIndentedString(mailRelay)).append("\n");
    sb.append("    mailSender: ").append(toIndentedString(mailSender)).append("\n");
    sb.append("    mailSubject: ").append(toIndentedString(mailSubject)).append("\n");
    sb.append("    smtpAuthPasswdSet: ").append(toIndentedString(smtpAuthPasswdSet)).append("\n");
    sb.append("    smtpAuthSecurity: ").append(toIndentedString(smtpAuthSecurity)).append("\n");
    sb.append("    smtpAuthUsername: ").append(toIndentedString(smtpAuthUsername)).append("\n");
    sb.append("    smtpPort: ").append(toIndentedString(smtpPort)).append("\n");
    sb.append("    useSmtpAuth: ").append(toIndentedString(useSmtpAuth)).append("\n");
    sb.append("    userTemplate: ").append(toIndentedString(userTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

