/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IdResolutionPath;
import io.swagger.client.model.IdResolutionPaths;
import io.swagger.client.model.IdResolutionPathsError;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * IdResolutionPathsExtended
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T15:41:52.549-07:00")
public class IdResolutionPathsExtended {
  @SerializedName("paths")
  private List<IdResolutionPath> paths = null;

  @SerializedName("errors")
  private List<IdResolutionPathsError> errors = null;

  @SerializedName("resume")
  private String resume = null;

  @SerializedName("total")
  private Integer total = null;

  public IdResolutionPathsExtended paths(List<IdResolutionPath> paths) {
    this.paths = paths;
    return this;
  }

  public IdResolutionPathsExtended addPathsItem(IdResolutionPath pathsItem) {
    if (this.paths == null) {
      this.paths = new ArrayList<IdResolutionPath>();
    }
    this.paths.add(pathsItem);
    return this;
  }

   /**
   * Get paths
   * @return paths
  **/
  @ApiModelProperty(value = "")
  public List<IdResolutionPath> getPaths() {
    return paths;
  }

  public void setPaths(List<IdResolutionPath> paths) {
    this.paths = paths;
  }

  public IdResolutionPathsExtended errors(List<IdResolutionPathsError> errors) {
    this.errors = errors;
    return this;
  }

  public IdResolutionPathsExtended addErrorsItem(IdResolutionPathsError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<IdResolutionPathsError>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<IdResolutionPathsError> getErrors() {
    return errors;
  }

  public void setErrors(List<IdResolutionPathsError> errors) {
    this.errors = errors;
  }

  public IdResolutionPathsExtended resume(String resume) {
    this.resume = resume;
    return this;
  }

   /**
   * Continue returning results from previous call using this token (token should come from the previous call, resume cannot be used with other options).
   * @return resume
  **/
  @ApiModelProperty(value = "Continue returning results from previous call using this token (token should come from the previous call, resume cannot be used with other options).")
  public String getResume() {
    return resume;
  }

  public void setResume(String resume) {
    this.resume = resume;
  }

  public IdResolutionPathsExtended total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Total number of items available.
   * minimum: 0
   * maximum: 4294967295
   * @return total
  **/
  @ApiModelProperty(value = "Total number of items available.")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdResolutionPathsExtended idResolutionPathsExtended = (IdResolutionPathsExtended) o;
    return Objects.equals(this.paths, idResolutionPathsExtended.paths) &&
        Objects.equals(this.errors, idResolutionPathsExtended.errors) &&
        Objects.equals(this.resume, idResolutionPathsExtended.resume) &&
        Objects.equals(this.total, idResolutionPathsExtended.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paths, errors, resume, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdResolutionPathsExtended {\n");
    
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    resume: ").append(toIndentedString(resume)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

