/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AuthGroupObjectHistoryItem;
import io.swagger.client.model.AuthIdNtokenPrivilegeItem;
import io.swagger.client.model.MappingUsersLookupMappingItemGroup;
import io.swagger.client.model.MappingUsersLookupMappingItemUser;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MappingUsersLookupMappingItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-18T15:45:33.897-07:00")
public class MappingUsersLookupMappingItem {
  @SerializedName("groups")
  private List<MappingUsersLookupMappingItemGroup> groups = null;

  @SerializedName("object_history")
  private List<AuthGroupObjectHistoryItem> objectHistory = null;

  @SerializedName("privileges")
  private List<AuthIdNtokenPrivilegeItem> privileges = null;

  @SerializedName("user")
  private MappingUsersLookupMappingItemUser user = null;

  @SerializedName("zid")
  private Integer zid = null;

  @SerializedName("zone")
  private String zone = null;

  public MappingUsersLookupMappingItem groups(List<MappingUsersLookupMappingItemGroup> groups) {
    this.groups = groups;
    return this;
  }

  public MappingUsersLookupMappingItem addGroupsItem(MappingUsersLookupMappingItemGroup groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<MappingUsersLookupMappingItemGroup>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public List<MappingUsersLookupMappingItemGroup> getGroups() {
    return groups;
  }

  public void setGroups(List<MappingUsersLookupMappingItemGroup> groups) {
    this.groups = groups;
  }

  public MappingUsersLookupMappingItem objectHistory(List<AuthGroupObjectHistoryItem> objectHistory) {
    this.objectHistory = objectHistory;
    return this;
  }

  public MappingUsersLookupMappingItem addObjectHistoryItem(AuthGroupObjectHistoryItem objectHistoryItem) {
    if (this.objectHistory == null) {
      this.objectHistory = new ArrayList<AuthGroupObjectHistoryItem>();
    }
    this.objectHistory.add(objectHistoryItem);
    return this;
  }

   /**
   * Get objectHistory
   * @return objectHistory
  **/
  @ApiModelProperty(value = "")
  public List<AuthGroupObjectHistoryItem> getObjectHistory() {
    return objectHistory;
  }

  public void setObjectHistory(List<AuthGroupObjectHistoryItem> objectHistory) {
    this.objectHistory = objectHistory;
  }

  public MappingUsersLookupMappingItem privileges(List<AuthIdNtokenPrivilegeItem> privileges) {
    this.privileges = privileges;
    return this;
  }

  public MappingUsersLookupMappingItem addPrivilegesItem(AuthIdNtokenPrivilegeItem privilegesItem) {
    if (this.privileges == null) {
      this.privileges = new ArrayList<AuthIdNtokenPrivilegeItem>();
    }
    this.privileges.add(privilegesItem);
    return this;
  }

   /**
   * Get privileges
   * @return privileges
  **/
  @ApiModelProperty(value = "")
  public List<AuthIdNtokenPrivilegeItem> getPrivileges() {
    return privileges;
  }

  public void setPrivileges(List<AuthIdNtokenPrivilegeItem> privileges) {
    this.privileges = privileges;
  }

  public MappingUsersLookupMappingItem user(MappingUsersLookupMappingItemUser user) {
    this.user = user;
    return this;
  }

   /**
   * Specifies the configuration properties for a user.
   * @return user
  **/
  @ApiModelProperty(value = "Specifies the configuration properties for a user.")
  public MappingUsersLookupMappingItemUser getUser() {
    return user;
  }

  public void setUser(MappingUsersLookupMappingItemUser user) {
    this.user = user;
  }

  public MappingUsersLookupMappingItem zid(Integer zid) {
    this.zid = zid;
    return this;
  }

   /**
   * Get zid
   * minimum: 0
   * maximum: 4294967295
   * @return zid
  **/
  @ApiModelProperty(value = "")
  public Integer getZid() {
    return zid;
  }

  public void setZid(Integer zid) {
    this.zid = zid;
  }

  public MappingUsersLookupMappingItem zone(String zone) {
    this.zone = zone;
    return this;
  }

   /**
   * Get zone
   * @return zone
  **/
  @ApiModelProperty(value = "")
  public String getZone() {
    return zone;
  }

  public void setZone(String zone) {
    this.zone = zone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MappingUsersLookupMappingItem mappingUsersLookupMappingItem = (MappingUsersLookupMappingItem) o;
    return Objects.equals(this.groups, mappingUsersLookupMappingItem.groups) &&
        Objects.equals(this.objectHistory, mappingUsersLookupMappingItem.objectHistory) &&
        Objects.equals(this.privileges, mappingUsersLookupMappingItem.privileges) &&
        Objects.equals(this.user, mappingUsersLookupMappingItem.user) &&
        Objects.equals(this.zid, mappingUsersLookupMappingItem.zid) &&
        Objects.equals(this.zone, mappingUsersLookupMappingItem.zone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groups, objectHistory, privileges, user, zid, zone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MappingUsersLookupMappingItem {\n");
    
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    objectHistory: ").append(toIndentedString(objectHistory)).append("\n");
    sb.append("    privileges: ").append(toIndentedString(privileges)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    zid: ").append(toIndentedString(zid)).append("\n");
    sb.append("    zone: ").append(toIndentedString(zone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

