/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NdmpLogsNode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-18T15:45:33.897-07:00")
public class NdmpLogsNode {
  @SerializedName("current_page")
  private String currentPage = null;

  @SerializedName("error")
  private String error = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("lnn")
  private Integer lnn = null;

  @SerializedName("logs")
  private String logs = null;

  @SerializedName("max_page")
  private Integer maxPage = null;

  @SerializedName("status")
  private Integer status = null;

  public NdmpLogsNode currentPage(String currentPage) {
    this.currentPage = currentPage;
    return this;
  }

   /**
   * The page on this node&#39;s NDMP log file being returned.
   * @return currentPage
  **/
  @ApiModelProperty(value = "The page on this node's NDMP log file being returned.")
  public String getCurrentPage() {
    return currentPage;
  }

  public void setCurrentPage(String currentPage) {
    this.currentPage = currentPage;
  }

  public NdmpLogsNode error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Error message, if the HTTP status returned from this node was not 200.
   * @return error
  **/
  @ApiModelProperty(value = "Error message, if the HTTP status returned from this node was not 200.")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public NdmpLogsNode id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Node ID of the node reporting this information.
   * minimum: 0
   * maximum: 4294967295
   * @return id
  **/
  @ApiModelProperty(value = "Node ID of the node reporting this information.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public NdmpLogsNode lnn(Integer lnn) {
    this.lnn = lnn;
    return this;
  }

   /**
   * Logical node number of the node reporting this information.
   * minimum: 0
   * maximum: 4294967295
   * @return lnn
  **/
  @ApiModelProperty(value = "Logical node number of the node reporting this information.")
  public Integer getLnn() {
    return lnn;
  }

  public void setLnn(Integer lnn) {
    this.lnn = lnn;
  }

  public NdmpLogsNode logs(String logs) {
    this.logs = logs;
    return this;
  }

   /**
   * The log file entries from the current page on this node.
   * @return logs
  **/
  @ApiModelProperty(value = "The log file entries from the current page on this node.")
  public String getLogs() {
    return logs;
  }

  public void setLogs(String logs) {
    this.logs = logs;
  }

  public NdmpLogsNode maxPage(Integer maxPage) {
    this.maxPage = maxPage;
    return this;
  }

   /**
   * The highest page number in this node&#39;s NDMP log file.
   * @return maxPage
  **/
  @ApiModelProperty(value = "The highest page number in this node's NDMP log file.")
  public Integer getMaxPage() {
    return maxPage;
  }

  public void setMaxPage(Integer maxPage) {
    this.maxPage = maxPage;
  }

  public NdmpLogsNode status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the HTTP response from this node if not 200.  If 200, this field does not appear.
   * minimum: 0
   * maximum: 4294967295
   * @return status
  **/
  @ApiModelProperty(value = "Status of the HTTP response from this node if not 200.  If 200, this field does not appear.")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NdmpLogsNode ndmpLogsNode = (NdmpLogsNode) o;
    return Objects.equals(this.currentPage, ndmpLogsNode.currentPage) &&
        Objects.equals(this.error, ndmpLogsNode.error) &&
        Objects.equals(this.id, ndmpLogsNode.id) &&
        Objects.equals(this.lnn, ndmpLogsNode.lnn) &&
        Objects.equals(this.logs, ndmpLogsNode.logs) &&
        Objects.equals(this.maxPage, ndmpLogsNode.maxPage) &&
        Objects.equals(this.status, ndmpLogsNode.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentPage, error, id, lnn, logs, maxPage, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NdmpLogsNode {\n");
    
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lnn: ").append(toIndentedString(lnn)).append("\n");
    sb.append("    logs: ").append(toIndentedString(logs)).append("\n");
    sb.append("    maxPage: ").append(toIndentedString(maxPage)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

