/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.NdmpSettingsVariablesVariable;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Get list of preferred environment variable.
 */
@ApiModel(description = "Get list of preferred environment variable.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T09:38:03.973-07:00")
public class NdmpSettingsVariables {
  @SerializedName("resume")
  private String resume = null;

  @SerializedName("total")
  private Integer total = null;

  @SerializedName("variables")
  private List<NdmpSettingsVariablesVariable> variables = null;

  public NdmpSettingsVariables resume(String resume) {
    this.resume = resume;
    return this;
  }

   /**
   * Resume string returned by previous query.
   * @return resume
  **/
  @ApiModelProperty(value = "Resume string returned by previous query.")
  public String getResume() {
    return resume;
  }

  public void setResume(String resume) {
    this.resume = resume;
  }

  public NdmpSettingsVariables total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * The number of backup paths.
   * @return total
  **/
  @ApiModelProperty(value = "The number of backup paths.")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public NdmpSettingsVariables variables(List<NdmpSettingsVariablesVariable> variables) {
    this.variables = variables;
    return this;
  }

  public NdmpSettingsVariables addVariablesItem(NdmpSettingsVariablesVariable variablesItem) {
    if (this.variables == null) {
      this.variables = new ArrayList<NdmpSettingsVariablesVariable>();
    }
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * Get variables
   * @return variables
  **/
  @ApiModelProperty(value = "")
  public List<NdmpSettingsVariablesVariable> getVariables() {
    return variables;
  }

  public void setVariables(List<NdmpSettingsVariablesVariable> variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NdmpSettingsVariables ndmpSettingsVariables = (NdmpSettingsVariables) o;
    return Objects.equals(this.resume, ndmpSettingsVariables.resume) &&
        Objects.equals(this.total, ndmpSettingsVariables.total) &&
        Objects.equals(this.variables, ndmpSettingsVariables.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resume, total, variables);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NdmpSettingsVariables {\n");
    
    sb.append("    resume: ").append(toIndentedString(resume)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

