/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ProvidersNisNisItemExtended;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ProvidersNisExtended
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T09:38:03.973-07:00")
public class ProvidersNisExtended {
  @SerializedName("nis")
  private List<ProvidersNisNisItemExtended> nis = null;

  public ProvidersNisExtended nis(List<ProvidersNisNisItemExtended> nis) {
    this.nis = nis;
    return this;
  }

  public ProvidersNisExtended addNisItem(ProvidersNisNisItemExtended nisItem) {
    if (this.nis == null) {
      this.nis = new ArrayList<ProvidersNisNisItemExtended>();
    }
    this.nis.add(nisItem);
    return this;
  }

   /**
   * Get nis
   * @return nis
  **/
  @ApiModelProperty(value = "")
  public List<ProvidersNisNisItemExtended> getNis() {
    return nis;
  }

  public void setNis(List<ProvidersNisNisItemExtended> nis) {
    this.nis = nis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProvidersNisExtended providersNisExtended = (ProvidersNisExtended) o;
    return Objects.equals(this.nis, providersNisExtended.nis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProvidersNisExtended {\n");
    
    sb.append("    nis: ").append(toIndentedString(nis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

