/*
 * Isilon SDK
 * Isilon SDK - Language bindings for the OneFS API
 *
 * OpenAPI spec version: 5
 * Contact: sdk@isilon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SnapshotAliasExtended
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-19T09:38:03.973-07:00")
public class SnapshotAliasExtended {
  @SerializedName("created")
  private Integer created = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("target_id")
  private Integer targetId = null;

  @SerializedName("target_name")
  private String targetName = null;

  public SnapshotAliasExtended created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * The Unix Epoch time the snapshot alias was created.
   * @return created
  **/
  @ApiModelProperty(required = true, value = "The Unix Epoch time the snapshot alias was created.")
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public SnapshotAliasExtended id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The system ID given to the snapshot alias.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "The system ID given to the snapshot alias.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public SnapshotAliasExtended name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The user or system supplied snapshot alias name.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The user or system supplied snapshot alias name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SnapshotAliasExtended targetId(Integer targetId) {
    this.targetId = targetId;
    return this;
  }

   /**
   * The ID of the snapshot pointed to.
   * @return targetId
  **/
  @ApiModelProperty(required = true, value = "The ID of the snapshot pointed to.")
  public Integer getTargetId() {
    return targetId;
  }

  public void setTargetId(Integer targetId) {
    this.targetId = targetId;
  }

  public SnapshotAliasExtended targetName(String targetName) {
    this.targetName = targetName;
    return this;
  }

   /**
   * The name of the snapshot pointed to.
   * @return targetName
  **/
  @ApiModelProperty(required = true, value = "The name of the snapshot pointed to.")
  public String getTargetName() {
    return targetName;
  }

  public void setTargetName(String targetName) {
    this.targetName = targetName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SnapshotAliasExtended snapshotAliasExtended = (SnapshotAliasExtended) o;
    return Objects.equals(this.created, snapshotAliasExtended.created) &&
        Objects.equals(this.id, snapshotAliasExtended.id) &&
        Objects.equals(this.name, snapshotAliasExtended.name) &&
        Objects.equals(this.targetId, snapshotAliasExtended.targetId) &&
        Objects.equals(this.targetName, snapshotAliasExtended.targetName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, id, name, targetId, targetName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SnapshotAliasExtended {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("    targetName: ").append(toIndentedString(targetName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

